version: "2"

linters:
  # Enable all default linters explicitly for consistency across environments
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - depguard # Not needed for this project

  settings:
    errcheck:
      check-blank: false
      check-type-assertions: false
      exclude-functions:
        - (io.Closer).Close
        - (*github.com/gofrs/flock.Flock).Unlock

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
