package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var shellSetupCmd = &cobra.Command{
	Use:   "shell-setup [shell]",
	Short: "Generate shell wrapper function for easier navigation",
	Long: `Generate shell wrapper function and completions for seamless worktree navigation.

Supported shells: zsh, bash, fish

Usage:
  # Add to your shell rc file:
  eval "$(wt shell-setup zsh)"    # ~/.zshrc
  eval "$(wt shell-setup bash)"   # ~/.bashrc
  wt shell-setup fish | source    # ~/.config/fish/config.fish

This sets up:
  - 'wt cd <branch>' command for seamless directory navigation
  - Tab completion for commands, branches, and flags`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var shell string
		if len(args) > 0 {
			shell = args[0]
		} else {
			shell = detectShell()
		}

		switch shell {
		case "zsh":
			fmt.Print(zshWrapper)
		case "bash":
			fmt.Print(bashWrapper)
		case "fish":
			fmt.Print(fishWrapper)
		default:
			return fmt.Errorf("unsupported shell: %s. Supported shells: zsh, bash, fish", shell)
		}
		return nil
	},
}

func detectShell() string {
	if shell := os.Getenv("SHELL"); shell != "" {
		if strings.Contains(shell, "zsh") {
			return "zsh"
		} else if strings.Contains(shell, "bash") {
			return "bash"
		} else if strings.Contains(shell, "fish") {
			return "fish"
		}
	}
	return "zsh" // Default to zsh
}

const zshWrapper = `# Generated by wt shell-setup
# Shell wrapper + completions for wt
wt() {
    if [ "$1" = "cd" ]; then
        local dir=$(command wt "$2")
        [ -d "$dir" ] && cd "$dir"
    else
        command wt "$@"
    fi
}
eval "$(command wt completion zsh)"
`

const bashWrapper = `# Generated by wt shell-setup
# Shell wrapper + completions for wt
wt() {
    if [ "$1" = "cd" ]; then
        local dir=$(command wt "$2")
        [ -d "$dir" ] && cd "$dir"
    else
        command wt "$@"
    fi
}
eval "$(command wt completion bash)"
`

const fishWrapper = `# Generated by wt shell-setup
# Shell wrapper + completions for wt
function wt
    if [ "$argv[1]" = "cd" ]
        set dir (command wt $argv[2])
        if test -d $dir
            cd $dir
        end
    else
        command wt $argv
    end
end
command wt completion fish | source
`

func init() {
	rootCmd.AddCommand(shellSetupCmd)
}
