package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var shellSetupCmd = &cobra.Command{
	Use:   "shell-setup [shell]",
	Short: "Generate shell wrapper function for easier navigation",
	Long: `Generate a shell wrapper function that adds 'wt cd' command for seamless worktree navigation.

Supported shells: zsh, bash, fish

Usage:
  wt shell-setup zsh >> ~/.zshrc
  wt shell-setup bash >> ~/.bashrc
  wt shell-setup fish >> ~/.config/fish/config.fish

After setup, use:
  wt cd feature/new-auth    # Creates if needed, cds, silent

This solves the shell limitation where a child process cannot change parent directory.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var shell string
		if len(args) > 0 {
			shell = args[0]
		} else {
			shell = detectShell()
		}

		switch shell {
		case "zsh":
			fmt.Print(zshWrapper)
		case "bash":
			fmt.Print(bashWrapper)
		case "fish":
			fmt.Print(fishWrapper)
		default:
			return fmt.Errorf("unsupported shell: %s. Supported shells: zsh, bash, fish", shell)
		}
		return nil
	},
}

func detectShell() string {
	if shell := os.Getenv("SHELL"); shell != "" {
		if strings.Contains(shell, "zsh") {
			return "zsh"
		} else if strings.Contains(shell, "bash") {
			return "bash"
		} else if strings.Contains(shell, "fish") {
			return "fish"
		}
	}
	return "zsh" // Default to zsh
}

const zshWrapper = `#!/bin/zsh
# Generated by wt shell-setup
# Adds 'wt cd' command for seamless worktree navigation
wt() {
    if [ "$1" = "cd" ]; then
        local dir=$(command wt "$2")
        [ -d "$dir" ] && cd "$dir"
    else
        command wt "$@"
    fi
}
`

const bashWrapper = `#!/bin/bash
# Generated by wt shell-setup
# Adds 'wt cd' command for seamless worktree navigation
wt() {
    if [ "$1" = "cd" ]; then
        local dir=$(command wt "$2")
        [ -d "$dir" ] && cd "$dir"
    else
        command wt "$@"
    fi
}
`

const fishWrapper = `# Generated by wt shell-setup
# Adds 'wt cd' command for seamless worktree navigation
function wt
    if [ "$argv[1]" = "cd" ]
        set dir (command wt $argv[2])
        if test -d $dir
            cd $dir
        end
    else
        command wt $argv
    end
end
`

func init() {
	rootCmd.AddCommand(shellSetupCmd)
}
